app/__init__.py
from flask import Flask, render_template
from app.views import main, ketcher, api


def create_app():
    """Create the Flask app."""

    app = Flask(__name__)
    app.register_blueprint(main)
    app.register_blueprint(ketcher, url_prefix='/ketcher')
    app.register_blueprint(api, url_prefix='/api/v1')

    # Error handling
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'), 404

    return app

app/views.py
from flask import Blueprint, send_from_directory, render_template
from flask import jsonify, request
import numpy as np
from predictor import Classifier
from lib.descriptor_gen import DescriptorGen
from rdkit import RDLogger
RDLogger.DisableLog('rdApp.*')

"""
Main views

- Home page
- About page
"""

main = Blueprint('main', __name__)


@main.route('/', methods=['GET'])
def index():
    """Render the home page."""

    return render_template('index.html')


@main.route('/about', methods=['GET'])
def about():
    """Render the about page."""

    return render_template('about.html')


"""
Ketcher views

- Serve the Ketcher web app
- Serve the Ketcher static files
"""


ketcher = Blueprint('ketcher', __name__)


@ketcher.route('/', methods=['GET'])
def serve_ketcher():
    """Serve the Ketcher web app."""

    return send_from_directory('static/ketcher', 'index.html')


@ketcher.route('/static/<path:filename>', methods=['GET'])
def serve_ketcher_static(filename):
    """Serve the Ketcher static files."""

    return send_from_directory('static/ketcher/static', filename)


"""
API views

- Predict endpoint
"""

api = Blueprint('api', __name__)


@api.route('/molecule-classifier/predict', methods=['POST'])
def predict():
    """Predict the class of a molecule given its SMILES string."""

    # Get the input data
    input_data = request.json
    smiles = input_data['smiles']

    if smiles == '':
        response = {
            'success': False,
        }
        return jsonify(response)

    # Generate the molecular descriptors
    desc_gen = DescriptorGen()
    desc = desc_gen.from_smiles(smiles)
    desc = np.stack(desc).reshape(1, -1)

    # Load the model
    model = Classifier()

    # Make prediction
    prediction = model.predict(desc)

    # Get the prediction class with the highest probability
    prediction_class = int(np.argmax(prediction))

    # Prepare the response
    label_map = {0: 'Activator', 1: 'Inactive', 2: 'Inhibitor'}
    response = {
        'success': True,
        'prediction_id': prediction_class,
        'prediction_class': label_map[prediction_class]
    }
    return jsonify(response)

app/templates/about.html
{% extends "base.html" %} {% block page_css %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/about.css') }}"
/>
{% endblock page_css %} {% block content %}
<div id="about">
  <h1>About</h1>
  <p>
    This is a web application that uses a machine learning model (LGBM) to
    classify molecules as Activator, Inhibitor, or Inactive. Draw a molecule in
    the Ketcher app and click the <code>SEND</code> button to classify it. The
    model was trained on a dataset from the NCATS CYP3A4 assay, which contains
    5,239 molecules.
  </p>
  <p>
    The model was trained using the <code>LightGBM</code> library, which is a
    gradient boosting framework that uses tree-based learning algorithms.
  </p>
  <p>
    This web application was developed using Flask, a micro web framework for
    Python. It uses the
    <a href="https://lifescience.opensource.epam.com/ketcher/">EPAM Ketcher</a>
    app to draw molecules and the <code>RDKit</code> library to convert the
    molecule SMILES string to a descriptor vector.
  </p>
</div>
{% endblock content %} {% block footer %}
<p class="copyright">© 2024 Molecule Classifier | Developed by Allan Almeida</p>
{% endblock footer %}

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/style.css')}}"
    />
    {% block page_css %}{% endblock page_css %}
    <link
      rel="icon"
      href="{{ url_for('static', filename='favicon.ico') }}"
      type="image/x-icon"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <title>Molecule Classifier</title>
  </head>

  <body>
    <header>
      <nav>
        <img
          id="logo"
          src="{{ url_for('static', filename='icon/android-chrome-192x192.png') }}"
          alt="Logo"
        />
        <h2>Molecule Classifier</h2>

        <div class="nav-items">
          <li><a href="{{ url_for('main.index')}}">Home</a></li>
          <li><a href="{{ url_for('main.about')}}">About</a></li>
        </div>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
    <footer>{% block footer %}{% endblock footer %}</footer>
    <script>
      const apiUrl = "{{ url_for('api.predict')}}";
    </script>
    <script src="{{ url_for('static', filename='js/index.js')}}"></script>
  </body>
</html>

app/templates/dialog.html
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/dialog.css') }}"
/>
<dialog id="welcomeDialog">
  <h2>Welcome to <code>Molecule Classifier</code></h2>
  <p>
    This is a web application that uses a machine learning model (LGBM) to
    classify molecules as Activator, Inhibitor, or Inactive.
  </p>
  <p>
    Draw a molecule in the Ketcher app and click the <code>SEND</code> button to
    classify it.
  </p>

  <p class="dialog-footer">
    <input type="checkbox" id="dontShow" name="dont-show" />
    <label for="dont-show"><b>Don't show this again</b></label>
  </p>
  <button onclick="closeDialog()" aria-label="close" class="x">❌</button>
</dialog>

app/templates/index.html
{% extends "base.html" %} {% block page_css %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/home.css') }}"
/>
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/loader.css') }}"
/>
{% endblock page_css %} {% block content %}
<iframe id="ifKetcher" src="{{ url_for('ketcher.serve_ketcher') }}"></iframe>
{% include "dialog.html" %} {% endblock content %} {% block footer %}
<div class="home-footer">
  <button onclick="sendMolecule()" id="send">SEND</button>
  <div id="helperText">Click the button to classify the molecule</div>
  <div id="loaderDots" class="loader"></div>
  <div id="resultDiv">
    <table id="resultTable">
      <tr>
        <td id="label">Prediction</td>
        <td id="prediction">Inactive [3]</td>
      </tr>
    </table>
    <div></div>
    {% endblock footer %}
  </div>
</div>